import { StyleSheet, Dimensions, StatusBar } from "react-native";

const { height: H, width: W } = Dimensions.get("screen");

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#FFF",
	},
	searchBarContainer: {
		position: "relative",
		width: "100%",
		height: 50,
	},
	searchBar: {
		width: "100%",
		height: "100%",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		borderBottomWidth: 1,
		borderBottomColor: "lightgrey",
	},
	searchListContainer: {
		position: "absolute",
		zIndex: 50,
		left: 0,
		top: 50,
		width: "100%",
		height: "auto",
		borderBottomWidth: 1,
		borderBottomColor: "lightgrey",
		backgroundColor: "#FFF",
		paddingVertical: 10,
		paddingHorizontal: 20,
	},
	searchTitleContainer: {
		width: "100%",
		height: "auto",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	searchLists: {
		position: "relative",
		width: "100%",
		height: "auto",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "flex-start",
		flexWrap: "wrap",
		marginTop: 10,
	},
	searchListBox: {
		paddingHorizontal: 15,
		paddingVertical: 4,
		borderRadius: 3,
		backgroundColor: "#F1F3F4",
	},
	searchListBoxText: {
		fontWeight: "600",
		color: "#00000090",
		fontSize: 14,
	},
	searchTitleText: {
		fontSize: 16,
		fontWeight: "700",
		color: "#000",
	},
	crrSearchLists: {
		position: "absolute",
		zIndex: 40,
		left: 0,
		top: 50,
		width: "100%",
		height: "auto",
		flexDirection: "column",
	},
	crrSearchListBox: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	backBtn: {
		width: "20%",
		height: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	textInputContainer: {
		width: "60%",
		height: "100%",
	},
	textInputText: {
		fontWeight: "600",
		color: "#000000",
		fontSize: 14,
		textAlign: "left",
	},
	searchTextContainer: {
		width: "20%",
		height: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	searchText: {
		fontSize: 14,
		fontWeight: "700",
		textTransform: "capitalize",
	},
	clearSearchFieldIconContainer: {
		position: "absolute",
		top: 0,
		right: -10,
		height: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		width: 50,
		zIndex: 20,
		backgroundColor: "transparent",
	},
	clearSearchFieldIcon: {
		position: "relative",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		width: 20,
		height: 20,
		backgroundColor: "#000",
		borderRadius: 24,
	},
	flatListContainer: {
		position: "relative",
		width: "100%",
		height: H - StatusBar.currentHeight - 50,
		backgroundColor: "transparent",
	},
	renderedBoxesContainer: {
		position: "relative",
		flexDirection: "row",
		flexWrap: "wrap",
		alignItems: "flex-start",
		justifyContent: "flex-start",
		backgroundColor: "#FFF",
	},
	renderedBox: {
		padding: 5,
		width: "50%",
		height: W / 2,
	},
	box: {
		width: "100%",
		height: "100%",
		borderRadius: 10,
		overflow: "hidden",
		borderWidth: 1,
		borderColor: "#F1F3F4",
		backgroundColor: "slightgrey",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
});

export { styles };
